language: python

python:
  - "2.7"
  - "3.5"

install: "make init"

before_script:
  - "export PYTHONPATH=${PYTHONPATH}:$(pwd)"

script:
  - "make check"
  - "make test"
  - "make source"
  - "pip install --upgrade dist/glibc-locale-tools-*.tar.gz"

notifications:
  email: false
  slack:
    rooms:
      secure: "Rse+KZpjFlG+ztNF2x0nb+mdckfG3ZMDt7/U7hoti6n3dG/5dGPuTWv53aU12zCC5uo5Owur3hmONqLAp+EOo+b8A5yxnTrjbDKo/GymCvtToXkcg6omlhEBZxcvKyKpGwjlRcx/ZXC6SRc5+NONLsgRnZQy/pDkxZ7WJhrj/yI="